/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2263;

public class App {
   

    public static void main(String[] args) {
<<<<<<< Updated upstream
        System.out.println(new App().getGreeting());
=======

>>>>>>> Stashed changes
    }
}
